name: ${project.name}
version: ${describe}
description: ${project.description}
authors: [md_5, ammar2]
website: ${project.url}

main: org.logblock.bukkit.LogBlock

commands:
  logblock:
    aliases: [lb]
    description: The core LogBlock command

permissions:
  logblock.command.*:
    description: Gives access to all LogBlock commands
