package org.logblock;

/**
 * DO NOT CHANGE THE ORDERING OF THIS ENUM IT WILL BREAK EVERYTHING.
 */
public enum Action
{

    BLOCK_BREAK,
    BLOCK_BURN,
    BLOCK_FALL,
    BLOCK_IGNITE,
    BLOCK_PISTON,
    BLOCK_PLACE,
    CONTAINER_ACCESS,
    ENTITY_CHANGE,
    EXPLOSION,
    LEAF_DECAY,
    NATURAL_BREAK,
    PLAYER_BUCKET,
    PLAYER_INTERACT,
    SIGN_TEXT,
    STRUCTURE_GROWTH,
    WORLDEDIT
}
